
[project]
name = "svk"
version = "1.0.0"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["test"]

markers = [
    "product: tests that generate products",
    "localproduct: tests that generate products locally",
    "wip: work in progress",
    ]